export const SET_TEXT = "SET_TEXT";

export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAILED = "AUTHENTICATE_FAILED";
export const AUTHENTICATE = "AUTHENTICATE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT = "LOGOUT";

export const REGISTRATION = "REGISTRATION";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const CHECKIFBANNED = "CHECKIFBANNED";
export const CHECKIFBANNED_SUCCESS = "CHECKIFBANNED_SUCCESS";
export const CHECKIFBANNED_FAILED = "CHECKIFBANNED_FAILED";

export const GETUSERSACTIVERES = "GETUSERSACTIVERES";
export const GETUSERSACTIVERES_SUCCESS = "GETUSERSACTIVERES_SUCCESS";
export const GETUSERSACTIVERES_FAILED = "GETUSERSACTIVERES_FAILED";

export const GETTINGSTADIUSM = "GETTINGSTADIUSM";
export const GETTINGSTADIUSM_SUCCESS = "GETTINGSTADIUSM_SUCCESS";
export const GETTINGSTADIUSM_FAILED = "GETTINGSTADIUSM_FAILED";
